### PR TITLE
`compile-sheets` recipe still exists if user chooses "No" to `use_schemasheets` during setup.

### PR DESCRIPTION
**Pull request by hrshdhgd**
As the code is set up now if a user selects 'No' for `use_schemasheets` during setup, the `compile-sheets` recipe is blank. This PR changes that and `gen-project` will just not have `compile-sheets` as a dependency.

### CODE REVIEW

**Comment by sierra-moxon** [comment]
Thanks so much @hrshdhgd!! I would be fine adding this to the cookie-cutter before the workshop.  But I'm also fine waiting.  @turbomam - could you weigh in?

**Comment by hrshdhgd** [comment]
Yeah, I had noticed this a while ago and meant to do this sooner. Sorry for the last minute update.

**Comment by cmungall** [comment]
I converted to draft while we decide but leave it up to you whether you want to bring in. May be too late on east coast for Mark though

**Comment by sierra-moxon** [comment]
ok - since its Mark's section that would need to change, lets just wait.

**Pull request merged**
