### PR TITLE
chore(readme): update click version

### PR DESCRIPTION
**Pull request by noelmcloughlin**
This PR bumps up click version

### CODE REVIEW

**Review by sierra-moxon — COMMENTED** [review]
Not sure how to test this is a non-breaking change.

**Comment by noelmcloughlin** [comment]
I'm not sure either. According to semver.org the change from 8.0 to 8.1 should be safe as long as click respects this convention.

    MAJOR version when you make incompatible API changes
    MINOR version when you add functionality in a backwards compatible manner
    PATCH version when you make backwards compatible bug fixes

https://click.palletsprojects.com/en/8.1.x/changes/#version-8-1-0

**Comment by sierra-moxon** [comment]
apologies, I think I merged in a change ahead of this one that requires you to fix the merged conflict on the command line.

**Review by sierra-moxon — APPROVED** [review]

**Comment by noelmcloughlin** [comment]
np, thanks @sierra-moxon

**Pull request merged**
