### PR TITLE
refactor: 4th use environment vars instead of about.yaml

### PR DESCRIPTION
**Pull request by noelmcloughlin**
This PR refactors how schema definition is passed to makefile.

- Move variables from `about.yaml` to `.env.public`
- Delete `about.yaml` and `utils/ directory` as not needed anymore
- Update `Makefile` to use environment variables from `.env.public.
- Run `check-config` as part of `make setup` to validate `include .env.public` worked

See https://github.com/linkml/linkml-project-cookiecutter/issues/57#issuecomment-1919916264

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
See comments in https://github.com/linkml/linkml-project-cookiecutter/issues/57

**Review by pkalita-lbl — COMMENTED** [review]
I made this as a comment in #57 before I looked at this PR, but I wonder if this is also a good opportunity to use a standard `.env` filename instead of `config.env`. Would be curious to get other LinkML developers' thoughts.

**Comment by noelmcloughlin** [comment]
I'd agree with that in this PR, good suggestion.  There is some open tooling which looks for a '.env' file, and auto loads environment cars if found. Chezmoi is one example, another called 'dotenv' I think.

There may also be value in using a standardized interface called '.config/' but need to think about that. It a standard for home directories, but I'm not 100% sure it's a standard for git repos.

**Comment by noelmcloughlin** [comment]
According to google search, .env may be best. There is also a .dotenv competing standard maybe, but I'd vote for .env

**Comment by noelmcloughlin** [comment]
@pkalita-lbl  Looks like `.env` may not be best choice, see https://configu.com/blog/dotenv-managing-environment-variables-in-node-python-php-and-more/#NoCommit

**Comment by noelmcloughlin** [comment]
Maybe `.env.public`  is semantic alternative?

**Comment by noelmcloughlin** [comment]
@pkalita-lbl   we can go ahead with `.env.public` for now.  PR is ready now.

**Review by pkalita-lbl — APPROVED** [review]
Great stuff!

**Comment by zmughal** [comment]
Just a note, when using a `.env`-style file in combination with GNU Make `include`, it must follow GNU Make syntax. If that file is meant to be sourced by `sh(1)`, then it must use only a common subset of that syntax (but that's not being done here).

Specifically, GNU Make retains any quotes as literal quotes whereas `sh(1)` does its own quoting. So any further use of these variables with functions (such as `$(dir ...)`) will be impacted such as with the `SOURCE_SCHEMA_DIR` variable which will start with a `"` character and end with a `/`. I have a fix for this as follows:

```patch
diff --git a/Makefile b/Makefile
index 26adc0a..cf84f7e 100644
--- a/Makefile
+++ b/Makefile
@@ -6,6 +6,10 @@ SHELL := bash
 .SUFFIXES:
 .SECONDARY:

+# define temporary variable for $(call ...)
+1 :=
+unquote = $(patsubst "%,%,$(patsubst %",%,$(1)))
+
 # environment variables
 .EXPORT_ALL_VARIABLES:
 ifdef LINKML_ENVIRONMENT_FILENAME
@@ -16,8 +20,8 @@ endif

 RUN = poetry run
 SCHEMA_NAME = $(LINKML_SCHEMA_NAME)
-SOURCE_SCHEMA_PATH = $(LINKML_SCHEMA_SOURCE_PATH)
-SOURCE_SCHEMA_DIR = $(dir $(SOURCE_SCHEMA_PATH))
+SOURCE_SCHEMA_PATH = $(call unquote,$(LINKML_SCHEMA_SOURCE_PATH))
+SOURCE_SCHEMA_DIR = $(patsubst %/,%,$(dir $(SOURCE_SCHEMA_PATH)))
 SRC = src
 DEST = project
 PYMODEL = $(SRC)/$(SCHEMA_NAME)/datamodel
```

I can make a PR for this.

The other solution is not use quotes on some of the variables (`LINKML_SCHEMA_SOURCE_PATH`), but that might confuse users as some variables don't follow the same pattern as others.

**Comment by zmughal** [comment]
This also affects `LINKML_SCHEMA_GOOGLE_SHEET_TABS`.

**Pull request merged**
